version: "3.9"

services:
  php:
    container_name: ${PROJECT_NAME:-solo}-${SERVICE_NAME:-service}-api-${API_VERSION:-1.0}-php
    build:
        context: .
        args:
          APP_ENV: ${APP_ENV}
        dockerfile: ./Dockerfile
        target: php_base
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - database
    labels:
      - "traefik.enable=false"
    volumes:
      - ./app:/app:rw

###> doctrine/doctrine-bundle ###
  database:
    container_name: ${PROJECT_NAME:-solo}-${SERVICE_NAME:-service}-db
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
      dockerfile: ./Dockerfile
      target: db_server
    env_file:
      - .env
    networks:
      default:
        aliases:
          - database
      database_network:
        aliases:
          - apikey_database
    labels:
      - "traefik.enable=false"
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app_db}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app_pwd}
#      POSTGRES_USER: ${POSTGRES_USER:-app_user}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  web:
    container_name: ${PROJECT_NAME:-solo}-${SERVICE_NAME:-service}-api-${API_VERSION:-1.0}-web
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
      dockerfile: ./Dockerfile
      target: nginx_server
    env_file:
      - .env
    networks:
      - proxy_network
      - default
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-${SERVICE_NAME}-http.entrypoints=web"
      - "traefik.http.middlewares.${PROJECT_NAME}-${SERVICE_NAME}-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}-${SERVICE_NAME}-https.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}-${SERVICE_NAME}-https.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-${SERVICE_NAME}-http.middlewares=${PROJECT_NAME}-${SERVICE_NAME}-https"
      - "traefik.http.middlewares.${PROJECT_NAME}-${SERVICE_NAME}-apiprefix.stripprefixregex.regex=/${SERVICE_NAME}/(?:api|proxy|dashboard|panel)/v[0-9]+(?:\\.[0-9]+)?/"
      - "traefik.http.routers.${PROJECT_NAME}-${SERVICE_NAME}-https.middlewares=${PROJECT_NAME}-${SERVICE_NAME}-apiprefix"
    volumes:
      - ./app/public:/app/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/.well-known/pki-validation:/var/www/.well-known/pki-validation
      - ./tmp/log/nginx/:/var/log/nginx

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
    name: ${PROJECT_NAME}_${SERVICE_NAME}_database_data
###< doctrine/doctrine-bundle ###

networks:
  proxy_network:
    name: ${PROXY_NETWORK}
    external: true
  database_network:
    name: ${PROXY_NETWORK}
    external: true
  default:
    name: ${APP_NETWORK}
    external: false
